version: '3.6'

services:
  frontend:
    restart: always
    image: "quay.io/openware/baseapp:2.6.24"
    volumes:
      - ../config/frontend/env.js:/usr/share/nginx/html/config/env.js
    labels:
      - "traefik.http.routers.frontend-opendax.rule=Host(`exe.wexplore3d.com`) && PathPrefix(`/`)"
      - "traefik.enable=true"
      - "traefik.http.services.frontend-opendax.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend-opendax.entrypoints=web"

  tower:
    restart: always
    image: "quay.io/openware/tower:2.6.66"
    volumes:
      - ../config/frontend/tower.js:/home/app/env.js
    labels:
      - "traefik.http.routers.tower-opendax.rule=Host(`exe.wexplore3d.com`) && PathPrefix(`/tower`)"
      - "traefik.enable=true"
      - "traefik.http.services.tower-opendax.loadbalancer.server.port=8080"
      - "traefik.http.routers.tower-opendax.entrypoints=web"
