version: '3.6'

services:
  superset:
    image: "amancevice/superset:0.28.1"
    restart: always
    volumes:
      - superset_db:/var/lib/superset
    labels:
      - "traefik.http.routers.superset-opendax.rule=Host(`superset.wexplore3d.com`)"
      - "traefik.http.services.superset-opendax.loadbalancer.server.port=8088"
      - "traefik.enable=true"
      - "traefik.http.routers.superset-opendax.entrypoints=web"

volumes:
  superset_db:
